### ISSUE TITLE
Add support for more languages?

### ISSUE THREAD

**Issue by bebraw** [vkbansal/illuminate-js#1]
Given the library is based on Prism, would it make sense to port the remaining language definitions over?

We're just discussing your library at https://github.com/mapbox/remark-react/issues/14 btw.

**Comment by vkbansal** [comment]
Thanks for your interest!

I developed this library for my personal use (my static blog). So I just added the languages that I use the most.

If there is enough interest and demand, I'm open to adding new language definitions.

Let me know, which languages you would like to see.

**Comment by bebraw** [comment]
On a quick look `makefile` is likely the only one I'm missing. I don't mind making a pull request once I need it, though.

I will follow https://github.com/mapbox/remark-react/issues/14 and make some moves when the time is right.

Btw, I wrote [prism-languages](https://github.com/survivejs/prism-languages). It wraps Prism language definitions in an easy to consume format. One option would be to push the problem there. You would simply consume that package. This would give us all Prism language definitions with very little effort.

**Comment by vkbansal** [comment]
I have made couple of changes to language definition structure, so using them directly will not be possible.

I'm also playing with the idea of making parser & definitions close to that of sublime-text/text-mate.

I'll try to put in `makefile` definition, over the weekend.

**Comment by bebraw** [comment]
Ok, cool. Thanks!

The original Prism definitions have some funkiness in them. I had to muck around with dependency loading order a lot to make the package work. Ideally we could push at least some of this work upstream somehow.

**Comment by vkbansal** [comment]
I've added `makefile` in `v0.3.0`.

Please open new issues for new languages.

**Comment by bebraw** [comment]
Cool. Thanks!
