### ISSUE TITLE
Add support for Sass

### ISSUE THREAD

**Issue by bebraw** [vkbansal/illuminate-js#10]
I can contribute this.

**Comment by vkbansal** [comment]
I already have SCSS, isn't the same?

**Comment by bebraw** [comment]
Sass is old, indented (think Python), syntax. SCSS won since. It's a little confusing.

I fixed this on my end (I found a place where I was using the wrong format).

**Comment by vkbansal** [comment]
If it is still required, I can add it. Else, please close this issue.

**Comment by bebraw** [comment]
Let’s close. It’s an ancient format.
