### ISSUE TITLE
Document advantages over Prism at readme

### ISSUE THREAD

**Issue by bebraw** [vkbansal/illuminate-js#3]
I noticed a while ago Prism Node API has improved. The language definitions are actually easy to use now.

If there are major differences still, it would be worthwhile to document those at the readme.

**Comment by vkbansal** [comment]
Prism was written when node wasn't mainstream (with browser first approach). It and it's plugins depend on `document` methods and other browser API.

I wrote this package for use with node and for my personal usage. I have no intent of making this main-stream and stealing `prism.js` users.

As for the API, it is very much experimental and may change drastically and hence deviate entirely from prism definitions.

If you use and like this package, your feedback will be very much appreciated.

**Comment by bebraw** [comment]
Ok, cool. I just thought it would be nice to state exactly things like that if/when people find this project. 👍

**Comment by vkbansal** [comment]
I have stated the same in README
