### ISSUE TITLE
Support for leanpub insert/delete

### ISSUE THREAD

**Issue by bebraw** [vkbansal/illuminate-js#7]
Hi,

I ported my `leanpub-start-insert`, `leanpub-end-insert` code to illuminate-js:

```javascript
addPlugin(addHook => {
  addHook("before-highlight", env => {
    env.code = env.code.replace(/leanpub-start-insert/gi, function(match) {
      return "_LEANPUB_START_INSERT";
    });

    env.code = env.code.replace(/leanpub-end-insert/gi, function(match) {
      return "_LEANPUB_END";
    });

    env.code = env.code.replace(/leanpub-start-delete/gi, function(match) {
      return "_LEANPUB_START_DELETE";
    });

    env.code = env.code.replace(/leanpub-end-delete/gi, function(match) {
      return "_LEANPUB_END";
    });
  });

  addHook("after-highlight", env => {
    env.highlightedCode = env.highlightedCode
      .replace(/_LEANPUB_START_INSERT/g, '<div class="leanpub-insert">')
      .replace(/_LEANPUB_START_DELETE/g, '<div class="leanpub-delete">')
      .replace(/_LEANPUB_END/g, "</div>");
  });
});
```

If you are interested, we could generalize this a bit and integrate it to the library. What do you think?

**Comment by vkbansal** [comment]
The plugin support is very experimental right now. I've not put much efforts into it. But your help will be appreciated.

**Comment by bebraw** [comment]
Ok, how about I generalize the plugin above and PR that? The interface looks good enough to me. I'm not a great fan of mutation but it's what Prism does so what can you do. 👍

**Comment by vkbansal** [comment]
That should work. I'm looking forward for your PR.

**Comment by bebraw** [comment]
Hi,

Here's a generalized version:

```javascript
module.exports = function replacePlugin({ start, end, className }) {
  const startReplacement = `_${start
    .replace(new RegExp("-", "g"), "_")
    .toUpperCase()}`;
  const endReplacement = `_${end
    .replace(new RegExp("-", "g"), "_")
    .toUpperCase()}`;

  return addHook => {
    addHook("before-highlight", env => {
      env.code = env.code
        .replace(new RegExp(start, "gi"), startReplacement)
        .replace(new RegExp(end, "gi"), endReplacement);
    });

    addHook("after-highlight", env => {
      env.highlightedCode = env.highlightedCode
        .replace(
          new RegExp(startReplacement, "g"),
          `<div class="${className}">`
        )
        .replace(new RegExp(endReplacement, "g"), "</div>");
    });
  };
};
```

**Usage:**

```javascript
addPlugin(
  replacePlugin({
    start: "leanpub-start-insert",
    end: "leanpub-end-insert",
    className: "leanpub-insert",
  })
);
addPlugin(
  replacePlugin({
    start: "leanpub-start-delete",
    end: "leanpub-end-delete",
    className: "leanpub-delete",
  })
);
```

I don't like all of the RegExp handling but it's enough for my use case.

What do you think? Should I generalize or tune it somehow?

**Comment by vkbansal** [comment]
Hey, I think  the original one is better and the second will be of little use to anyone else.

Also, Can you publish this plugin separately?

**Comment by bebraw** [comment]
Hi,

I can publish it separately, yeah. I kind of like the generic version. You can always write a more specific wrapper for it to match the first implementation since it's functionally the same.

I'll close this once the plugin is up. Quite busy at the moment.

**Comment by bebraw** [comment]
Time to close. If anyone needs the code, feel free to copy from above - no attribution needed. 👍
